#!/usr/bin/env python3
"""Emit the extra outfit colours for src/ZCOMOpenKit/src/colour_table.inc.

Sternab's Expanded Colours offers 40 of the game's 335 locked outfit colours,
curated by eye. The curation is sound as far as it goes -- most of the rest are
not new colours at all -- but it leaves out a lot that genuinely is. This script
finds those, so the extra palette is derived from the game rather than picked.

    ./scripts/generate-colour-table.py <json-tree> > src/ZCOMOpenKit/src/colour_table.inc

## The rule, and why it is a distance rather than a list

Every colour part carries one FLinearColor. A locked colour is worth offering
only if a player cannot already pick something indistinguishable from it, so
each is measured against all 119 colours the game does offer and kept when the
nearest is at least 0.05 away in linear RGB.

    < 0.02   82 parts   the same colour as one already available
    < 0.05  126 parts   too close to tell apart in a picker swatch
    >= 0.05 127 parts   worth offering, of which upstream already has 26

## What is excluded by name, matching upstream's own exclusions

    Tester_A/B/G/R          developer test swatches, pure R/G/B/A ramps
    SlugratRed, _Lite       a character-specific colour, not a palette entry

Weapon paints are not handled here: the game locks 90 and upstream offers all
90, so there is nothing left to add.
"""

import glob
import json
import math
import os
import re
import sys

EXCLUDE = re.compile(r"_(Tester_[ABGR]|SlugratRed(_Lite)?)$")
PREFIX = "CPD_H_Outfit_Color_"


def number(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def read(path):
    name = os.path.basename(path)[:-5]
    asset = json.loads(open(path).read())
    locked, rgb = False, None
    for export in asset.get("Exports") or []:
        if not isinstance(export, dict):
            continue
        for prop in export.get("Data") or []:
            if not isinstance(prop, dict):
                continue
            if prop.get("Name") == "AllowedSlots" and export.get("ObjectName") == name:
                locked = "AuthoredOnly" in json.dumps(prop)
            if prop.get("Name") == "Color":
                value = prop.get("Value") or []
                colour = value[0].get("Value") if value and isinstance(value[0], dict) else None
                if isinstance(colour, dict):
                    channels = [number(colour.get(k)) for k in ("R", "G", "B")]
                    if all(c is not None for c in channels):
                        rgb = tuple(channels)
    return name, locked, rgb


def label_for(name):
    """CPD_H_Outfit_Color_CoolGrey_03 -> "Cool Grey 03"."""
    stem = name[len(PREFIX):]
    suffix = ""
    match = re.search(r"_(\d+)$", stem)
    if match:
        suffix = " " + match.group(1)
        stem = stem[: match.start()]
    words = re.findall(r"[A-Z][a-z]*|\d+", stem) or [stem]
    return " ".join(words) + suffix


def main(tree, upstream_source):
    offered = set(re.findall(r'STR\("(CPD_H_Outfit_Color_[^"]+)"\)',
                             open(upstream_source).read()))
    parts = [read(f) for f in glob.glob(os.path.join(tree, "CPD_H_Outfit_Color_*.json"))]
    available = [rgb for _, locked, rgb in parts if not locked and rgb]
    if not available:
        raise SystemExit("no unlocked colours found -- wrong tree?")

    def nearest(rgb):
        return min(math.sqrt(sum((a - b) ** 2 for a, b in zip(rgb, other)))
                   for other in available)

    rows, excluded = [], 0
    for name, locked, rgb in parts:
        if not locked or rgb is None or name in offered:
            continue
        if nearest(rgb) < 0.05:
            continue
        if EXCLUDE.search(name):
            excluded += 1
            continue
        rows.append((label_for(name), name))

    print("// Generated by scripts/generate-colour-table.py -- do not edit by hand.")
    print("// Locked outfit colours that upstream does not offer and that are at least")
    print("// 0.05 away in linear RGB from every colour the game already offers.")
    print(f"// {len(rows)} rows.")
    for label, name in sorted(rows):
        print(f'    {{STR("{name}"), STR("{label}")}},')

    print(f"\n// {len(rows)} extra colours, {excluded} excluded by name "
          f"(developer test swatches and character-specific colours)", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
